# Generated by Django 3.0.6 on 2020-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200530_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_on',
            field=models.DateTimeField(),
        ),
    ]
