# Generated by Django 3.0.6 on 2020-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200530_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
